###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: dinobits-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: docker/php-fpm
      container_name: dinobits-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: dinobits_root!dinobits_root
        MYSQL_DATABASE: dinobits
        MYSQL_USER: dinobits
        MYSQL_PASSWORD: dinobits!dinobits
      ports:
        - "9906:3306"
