twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        author: '%env(WEB_AUTHOR)%'
        description: '%env(WEB_DESCRIPTION)%'