twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        author: '%env(WEB_AUTHOR)%'
        description: '%env(WEB_DESCRIPTION)%'